config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  get 'gallery/index'
  resources :stores
  get 'admin/login'
  post 'admin/login'
  get 'admin/logout'
  get 'admin/log'
  get 'gallery/contact'
  get 'gallery/products'
  get 'gallery/tracking'
  get 'gallery/index'
  get 'gallery/checkout'
  post 'gallery/checkout'
  get 'gallery/purchased'
  get 'gallery/search'
  post 'gallery/search'
  # post 'gallery/view_order/:order_id', to: 'gallery#view', as: :gallery_view_order

  devise_for :users
  root to: 'gallery#index'
  get 'gallery/view/:id', to: 'gallery#view', as: 'view_product_detail'
  post 'gallery/view/:id', to: 'gallery#view', as: 'post_view_product'
  get 'admin_login', to: 'admin_sessions#new'
  post 'admin_login', to: 'admin_sessions#create'
  get 'admin_logout', to: 'admin_sessions#delete'
end

app/models/store.rb
class Store < ApplicationRecord
    has_one_attached :store_image
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]
  before_action :authenticate_admin, except: [:login]


  # GET /stores or /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to store_url(@store), notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to store_url(@store), notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:name, :color, :brand, :size, :description, :price, :store_image)
    end

    def authenticate_admin
      unless session[:admin_logged_in]
        redirect_to '/admin/login', alert: "You are not logged in."
      end
    end
    
    def admin_logged_in?
  
      if session[:admin].nil?
   
       flash[:notice] = "You need to login as an admin to continue...."
   
       redirect_to admin_login_url
   
      end
   
     end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<section class="banner-area">
		<div class="container">
			<div class="row fullscreen align-items-center justify-content-start">
				<div class="col-lg-12">
					<div class="active-banner-slider owl-carousel">
						<!-- single-slide -->
						<div class="row single-slide align-items-center d-flex">
							<div class="col-lg-5 col-md-6">
								<div class="banner-content">
                  <div class="form-container">
                    <% if session[:admin_logged_in] %>
    <a href="/admin/logout"> Admin Logout</a> 
  <% else %>
      <a href="/admin/login"> Admin Login</a> 
  <% end %>
  <p id="notice"><%= notice %></p>
                    <h3>Store</h3>
                    <br>
                    <%= form_with(model: store) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :color %><br>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :brand %><br>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :size %><br>
    <%= form.text_field :size %>
  </div>

  <div class="field">
    <%= form.label :desc %><br>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </div>

  <div class="field">
   <%= form.label :image %><br>
   <%= form.file_field :store_image %>
 </div>

  <div class="actions">
    <br>
    <%= form.submit %><br><br>
    <%= link_to 'Back', stores_path %>
  </div>
  
<% end %>
                </div>
								</div>
							</div>
							<div class="col-lg-7">
								<div class="banner-img">
									<img class="img-fluid" src="/assets/banner/banner-img.png" alt="">
								</div>
							</div>
						</div>
            
						<!-- single-slide -->
						

app/views/stores/edit.html.erb
<%= render 'form', store: @store %>

<%# <%= link_to 'Show', @store %> |
<%#= link_to 'Back', stores_path %> 

app/views/stores/index.html.erb
<!-- Start Banner Area -->
    <section class="banner-area organic-breadcrumb">
        <div class="container">
            <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                <div class="col-first">
                    <h1>Shoes Stores</h1>
                    <nav class="d-flex align-items-center">
                        <a href="index.html">Admin<span class="lnr lnr-arrow-right"></span></a>
                        <a href="category.html">Stores</a>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Banner Area -->

    <!--================Cart Area =================-->
<section class="cart_area">
    <div class="container">
        <div class="cart_inner">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Image</th>
                            <th scope="col">Name</th>
                            <th scope="col">Color</th>
                            <th scope="col">Brand</th>
                            <th scope="col">Size</th>
                            <th scope="col">Description</th>
                            <th scope="col">Price</th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
    <br>
    <% @stores.each do |store| %>
      <tr>
        <td><%= image_tag store.store_image ,:height=>"100",:width=>"100" if store.store_image.attached? %></td>
        <td><%= store.name %></td>
        <td><%= store.color %></td>
        <td><%= store.brand %></td>
        <td><%= store.size %></td>
        <td><%= store.description %></td>
        <td><%= store.price %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
                    </tbody>
                    </table>
                                        <%= link_to "New Shoes", new_store_path, class: "btn btn-success" %>

                </div>
            </div>
        </div>
    </section>
    <!--================End Cart Area =================-->

app/views/stores/new.html.erb
<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<section class="banner-area">
		<div class="container">
			<div class="row fullscreen align-items-center justify-content-start">
				<div class="col-lg-12">
					<div class="active-banner-slider owl-carousel">
						<!-- single-slide -->
						<div class="row single-slide align-items-center d-flex">
							<div class="col-lg-5 col-md-6">
								<div class="banner-content">
                  <div class="stores-form">
					<% if session[:admin_logged_in] %>
    <a href="/admin/logout"> Admin Logout</a> 
  <% else %>
      <a href="/admin/login"> Admin Login</a> 
  <% end %>
  <p id="notice"><%= notice %></p>


<p>
  <%= image_tag @store.store_image ,height:"200", width:"200" %>
  <br>
</p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @store.color %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @store.brand %>
</p>

<p>
  <strong>Size:</strong>
  <%= @store.size %>
</p>

<p>
  <strong>Description:</strong>
  <%= @store.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @store.price %>
</p>
<br>

<%= link_to 'Edit', edit_store_path(@store) %> ---
<%= link_to 'Back', stores_path %>
</div>
								</div>
							</div>
							<div class="col-lg-7">
								<div class="banner-img">
									<img class="img-fluid" src="/assets/banner/banner-img.png" alt="">
								</div>
							</div>
						</div>
						<!-- single-slide -->
						