config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  get 'gallery/index'
  resources :stores
  get 'admin/login'
  post 'admin/login'
  get 'admin/logout'
  get 'admin/log'
  get 'gallery/contact'
  get 'gallery/products'
  get 'gallery/tracking'
  get 'gallery/index'
  get 'gallery/checkout'
  post 'gallery/checkout'
  get 'gallery/purchased'
  get 'gallery/search'
  post 'gallery/search'
  # post 'gallery/view_order/:order_id', to: 'gallery#view', as: :gallery_view_order

  devise_for :users
  root to: 'gallery#index'
  get 'gallery/view/:id', to: 'gallery#view', as: 'view_product_detail'
  post 'gallery/view/:id', to: 'gallery#view', as: 'post_view_product'
  get 'admin_login', to: 'admin_sessions#new'
  post 'admin_login', to: 'admin_sessions#create'
  get 'admin_logout', to: 'admin_sessions#delete'
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :store

  def total_price
		store.price * quantity
	end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: %i[ show edit update destroy ]

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
    @shoes_gallery = Store.all # Or some other way to fetch the shoes data
    
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create
    # @line_item = LineItem.new(line_item_params)
    @cart = current_cart
	  product = Store.find(params[:store_id])
	  @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to line_items_url, notice: "Line item was successfully created." }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to line_item_url(@line_item), notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
         
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url, notice: "Line item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:cart_id, :store_id, :quantity)
    end
  
    private
  
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<section class="banner-area">
		<div class="container">
			<div class="row fullscreen align-items-center justify-content-start">
				<div class="col-lg-12">
					<div class="active-banner-slider owl-carousel">
						<!-- single-slide -->
						<div class="row single-slide align-items-center d-flex">
							<div class="col-lg-5 col-md-6">
								<div class="banner-content">
                  <div class="hello">
                    <h3>Edit Form</h3>
                  <%= form_with(model: line_item) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>
<br>
  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id %>
  </div>

  <div class="field">
    <%= form.label :store_id %>
    <%= form.text_field :store_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
                </div>
								</div>
							</div>
							<div class="col-lg-7">
								<div class="banner-img">
									<img class="img-fluid" src="/assets/banner/banner-img.png" alt="">
								</div>
							</div>
						</div>
						<!-- single-slide -->

app/views/line_items/_line_item.html.erb
<tr>
	<td><%= line_item.quantity %> &times;</td>
	<td><%= line_item.store.name %></td>
	<td class="item_price"><%= number_to_currency(line_item.total_price) %></td>
</tr>

app/views/line_items/edit.html.erb
<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
    <!-- Start Banner Area -->
    <section class="banner-area organic-breadcrumb">
        <div class="container">
            <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                <div class="col-first">
                    <h1>Shopping Cart</h1>
                    <nav class="d-flex align-items-center">
                        <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                        <a href="category.html">Cart</a>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Banner Area -->

    <!--================Cart Area =================-->
<section class="cart_area">
    <div class="container">
        <div class="cart_inner">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Product</th>
                            <th scope="col">Price</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Total</th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @line_items.each do |line_item| %>
                            <% shoe = line_item.store %>
                            <tr data-line-item-id="<%= line_item.id %>">
                            <tr>
                                <td>
                                    <div class="media">
                                        <div class="d-flex">
                                            <%= image_tag shoe.store_image, height: "150", width: "150" if shoe.store_image.attached? %><br />
                                        </div>
                                        <div class="media-body">
                                            <p><%= shoe.name %></p>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <h5><%= shoe.price %></h5>
                                </td>
                                <td>
                                    <div class="product_count">
                                        <input type="number" name="qty" class="input-text qty" data-line-item-id="<%= line_item.id %>"
                                value="<%= line_item.quantity %>" min="1" title="Quantity:" readonly>
                                        
                                    </div>
                                </td>
                                <td>
                                    <h5><%= line_item.total_price %></h5>
                                    
                                </td>
                                 <td>
                                    <%= link_to 'Edit', edit_line_item_path(line_item) %>
                                </td>
                                <td>
                                  <%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %>
                                </td>

                            </tr>
                        <% end %>

                        <tr>
                            <td></td>
                            <td></td>
                            <td>
                                <h5>Total</h5>
                            </td>
                            <td>
                                <% session[:amount] = @line_items.sum(&:total_price) %>
                                <h5><%= @line_items.sum(&:total_price) %></h5>
                            </td>
                        </tr>
                            
                                
                            <tr class="out_button_area">
                                <td>

                                </td>
                                <td>

                                </td>
                                <td>

                                </td>
                                <td>
                                    <div class="checkout_btn_inner d-flex align-items-center">
                                        <a class="gray_btn" href="/">Continue Shopping</a>
                                        <a class="primary-btn" href="gallery/checkout">Proceed to checkout</a>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
    <!--================End Cart Area =================-->

 

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
 

<section class="banner-area">
		<div class="container">
			<div class="row fullscreen align-items-center justify-content-start">
				<div class="col-lg-12">
					<div class="active-banner-slider owl-carousel">
						<!-- single-slide -->
						<div class="row single-slide align-items-center d-flex">
							<div class="col-lg-5 col-md-6">
								<div class="banner-content">
                  <div class="hello">
                    <h3>Show Shoe</h3>
                  <p id="notice"><%= notice %></p>
<p>
  <strong>Image:</strong>
  <%= @line_item.store_id%>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<p>
  <strong>Store:</strong>
  <%= @line_item.store_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @line_item.quantity %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>
                </div>
								</div>
							</div>
							<div class="col-lg-7">
								<div class="banner-img">
									<img class="img-fluid" src="/assets/banner/banner-img.png" alt="">
								</div>
							</div>
						</div>
						<!-- single-slide -->

 